#+title: Roc Mode
#+subtitle: Roc programming language mode for Emacs

Roc is a strongly typed functional programming language inspired by Elm, but for variety of platforms. See [[https://www.roc-lang.org/][https://www.roc-lang.org/]].

This is a friendly fork of [[https://gitlab.com/tad-lispy/roc-mode][the original roc-mode]] by [[https://tad-lispy.com/][tad-lispy]].

* Disclaimer

This code is an early work in progress and I am a novice at Emacs Lisp. Polite suggestions and contributions are welcome.

* Install

Currently only installation from the Git repository is possible.

Requirements: Emacs 29.1+.

** In Doom Emacs

Add the following to ~packages.el~ (use ~doom/find-file-in-private-config~ typically bound to ~SPC f p~):

#+begin_src emacs-lisp :noeval
;;original package:
;; (package! roc-mode :recipe (:host gitlab :repo "tad-lispy/roc-mode"))
;;this fork:
(package! roc-mode :recipe (:host gitlab :repo "AjaiKN/roc-mode"))
#+end_src

Then, run ~M-x roc-mode-install-treesit-grammar~ (or install the Roc tree-sitter grammar another way).

*** Recommended configuration for Doom Emacs

Add the following to ~config.el~ (use ~doom/find-file-in-private-config~ typically bound to ~SPC f p~):

#+begin_src emacs-lisp :noeval
(use-package! roc-mode
  :mode ("\\.roc\\'" . roc-mode)
  :config
  (map! :map roc-mode-map
        (:localleader
         "f" #'roc-mode-format
         "b" #'roc-mode-build
         "t" #'roc-mode-test
         "r" #'roc-mode-run
         "d" #'roc-mode-dev
         "c" #'roc-mode-check
         "e" #'roc-repl))

  (set-popup-rule! (rx bol "*roc-repl") :size 0.3)

  ;; Setup the LSP support
  (when (and (modulep! :tools lsp) (not (modulep! :tools lsp +eglot)))
    (require 'lsp-mode)
    (add-to-list 'lsp-language-id-configuration '(roc-mode . "roc"))
    (lsp-register-client (make-lsp-client :new-connection (lsp-stdio-connection "roc_language_server")
                                          :activation-fn (lsp-activate-on "roc")
                                          :major-modes '(roc-mode)
                                          :server-id 'roc_ls)))
  (when (modulep! :tools lsp +eglot)
    (set-eglot-client! 'roc-mode '("roc_language_server")))
  (add-hook 'roc-mode-local-vars-hook #'lsp!)

  ;; Formatting
  (set-formatter! 'roc-format '("roc" "format" "--stdin" "--stdout") :modes '(roc-mode))
  (setq-hook! 'roc-mode-local-vars-hook
    +format-with 'roc-format)

  ;; Keywords that should trigger electric indentation
  (set-electric! 'roc-mode :words '("else"))

  ;; Extra ligatures
  (when (modulep! :ui ligatures +extra)
    (set-ligatures! 'roc-mode
      :true "Bool.true" :false "Bool.false"
      :not "!"
      :and "&&" :or "||")
    (setq-hook! 'roc-mode-hook
      prettify-symbols-compose-predicate #'+roc-mode-symbol-compose-p)
    (defun +roc-mode-symbol-compose-p (start end match)
      "Like `prettify-symbols-default-compose-p', except that if the
match is !, it checks that it's a logical NOT rather than the !
suffix operator (syntactic sugar for Task.await; see URL
  `https://www.roc-lang.org/tutorial#the-!-suffix')."
      (and (prettify-symbols-default-compose-p start end match)
           (or (not (equal match "!"))
               (and
                ;; character before isn't a word character
                (not (eq (char-syntax (char-before start))
                         ?w))
                ;; character after is a word character or open paren
                (memq (char-syntax (char-after end))
                      '(?\( ?w))))))))
#+end_src

See also [[https://gitlab.com/tad-lispy/nixos-configuration/-/tree/main/doom-emacs/modules/lang/roc][tad-lispy's private module for Roc]].

** Using straight

#+begin_src emacs-lisp
;;original package:
;; (straight-use-package '(roc-mode :type git :host gitlab :repo "tad-lispy/roc-mode"))
;;this fork:
(straight-use-package '(roc-mode :type git :host gitlab :repo "AjaiKN/roc-mode"))
#+end_src

Then, run ~M-x roc-mode-install-treesit-grammar~ (or install the Roc tree-sitter grammar another way).

** TODO vanilla Emacs

Once the package is published to MELPA, it should be possible to install it with built-in ~install-package~, and ~straight~ shouldn't be a requirement any longer. For now, you can manually clone this repository and add it to your ~load-path~.

Then, run ~M-x roc-mode-install-treesit-grammar~ (or install the Roc tree-sitter grammar another way).

*** Basic configuration

Add the following to your ~init.el~:

#+begin_src emacs-lisp :noeval

(use-package! roc-mode
  :mode ("\\.roc\\'" . roc-mode)
  :config
  ;; any configuration goes here (e.g., see below for language server integration)...
  )
#+end_src

* Features

** STRT Syntax highlighting

Partially done.

After installing the package you need to install the Tree Sitter grammar. Run ~treesit-install-language-grammar~ and select ~roc~. This should give you syntax highlighting.

Question: Should this be automated?

Relevant discussion: https://lists.gnu.org/archive/html/emacs-devel/2023-11/msg01365.html

** STRT Indentation rules

Tree sitter is used to make some basic indentation rules that aim to be consistent with "roc format", and there are tests to check that consistency. It's still a work in progress, though.

** TODO Language server integration

NOTE: If you're using Doom Emacs, the recommended configuration above already supports this.

*** Option 1: Eglot

Emacs 29 comes with a built-in LSP client called Eglot. To integrate with it, add the following to your configuration:

#+begin_src emacs-lisp :noeval
(with-eval-after-load 'roc-mode
  (require 'eglot)
  (add-to-list 'eglot-server-programs '(roc-mode "roc_language_server"))
  (add-hook 'roc-mode-hook #'eglot-ensure))
#+end_src

*** Option 2: LSP Mode

First, [[https://emacs-lsp.github.io/lsp-mode/page/installation/][install lsp-mode]] if you haven't. Then add the following to your configuration:

#+begin_src emacs-lisp :noeval
(with-eval-after-load 'roc-mode
  (require 'lsp-mode)
  (add-to-list 'lsp-language-id-configuration '(roc-mode . "roc"))
  (lsp-register-client (make-lsp-client :new-connection (lsp-stdio-connection "roc_ls")
                                        :activation-fn (lsp-activate-on "roc")
                                        :major-modes '(roc-mode)
                                        :server-id 'roc_ls))
  (add-hook 'roc-mode-hook #'lsp-deferred))
#+end_src

** Roc CLI commands

You can use the following keybindings to run Roc CLI commands.

| Default keybinding | Emacs ~roc-mode~ command | CLI command   | Description                                            |
|--------------------+--------------------------+---------------+--------------------------------------------------------|
| ~C-c C-f~          | ~roc-mode-format~        | ~roc format~  | Format the current buffer                              |
| ~C-c C-b~          | ~roc-mode-build~         | ~roc build~   | Build the current file                                 |
| ~C-c C-t~          | ~roc-mode-test~          | ~roc test~    | Test the current file                                  |
| ~C-c C-r~          | ~roc-mode-run~           | ~roc run~     | Run tests in the current file (and modules it imports) |
| ~C-c C-d~          | ~roc-mode-dev~           | ~roc dev~     | Check current file, then run if no errors              |
| ~C-c C-c~          | ~roc-mode-check~         | ~roc check~   | Check current file for errors                          |
| ~C-c C-e~          | ~roc-mode-repl~         | ~roc repl~   | Open a Roc REPL buffer    |
| N/A                | ~roc-mode-version~       | ~roc version~ | Print and copy the current version of Roc              |

* License

GPLv3

